version: '3'

services:
  app:
    build:
      context: ./src/dockerfile
    ports:
      - ${HTTP_PORT:-8000}:80
      - 5173:5173
    volumes:
      - ./src/laravel:/var/www/html
      - ./entrypoint.sh:/tmp/entrypoint.sh
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules 
    secrets:
      - host_ssh_key
    entrypoint: "/tmp/entrypoint.sh"
    command: "apache2-foreground"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: passwd
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT:-3306}:3306
  mailhog:
   image: 'mailhog/mailhog:latest'
   ports:
     - '8025:8025'

volumes:
  vendor:
  node_modules:
  db_data:

secrets:
  host_ssh_key:
    file: ${SSH_KEY_PATH:-key}