version: '3'

services:
  app:
    build:
      context: ./src/dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-8.1}"
    ports:
      - 8000:80
      - 5173:5173
    volumes:
      - ./src/laravel:/var/www/html
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY:-12345678901234567890123456789012}
      - APP_ENV=local
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=passwd
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: passwd
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  mailhog:
   image: 'mailhog/mailhog:latest'
   ports:
     - '8025:8025'